### ISSUE TITLE
No horizontal scrolling bar

### ISSUE THREAD

**Issue by MarcAnt01** [luandersonn/Modern-scrollbar#1]
When enabling the extension I can't use the horizontal scrolling bar

**Comment by luandersonn** [comment]
Are you sure it's due to the extension? Horizontal and Vertical scrolling is working fine here (mouse wheel, touchpad gesture and dragging the scrollbar).

**Comment by MarcAnt01** [comment]
I checked and it seems an Edge issue, not due to your extension, sorry.
