### ISSUE TITLE
Scrollbar buttons still shown when an overflow element is set to "scroll" even without scrollbar

### ISSUE THREAD

**Issue by win98se** [luandersonn/Modern-scrollbar#10]
The affected elements all have their `overflow-y` value set to `scroll`. This is since #9 is implemented.

Browser: Microsoft Edge 92.0.902.62

![image](https://user-images.githubusercontent.com/11819816/128373156-bba3fa4e-604f-4404-ab59-635471dc384f.png)

**Comment by luandersonn** [comment]
#49b6abe

**Comment by luandersonn** [comment]
49b6abe

**Comment by win98se** [comment]
Follow up: Greetings. Is the Edge Store version this extension will not updated yet? I still see 1.0.0.4 here.

**Comment by luandersonn** [comment]
> Follow up: Greetings. Is the Edge Store version of this extension still not updated yet? I still see 1.0.0.4 here.

Microsoft is a little bit more slower to approve updates.
