### ISSUE TITLE
youtube scrollbar not funtion

### ISSUE THREAD

**Issue by zhenjie1999** [luandersonn/Modern-scrollbar#11]
device and website also white theme but showing dark scrollbar
![image](https://user-images.githubusercontent.com/75268245/128623671-171d146c-eec1-48a6-9962-6107d7ac7c17.png)

**Comment by luandersonn** [comment]
This is because YouTube uses its own scroll bar. This scrollbar that is in the image is one customized by YouTube itself.

When the website makes its own change to the scrollbar, that change overwrites the change from extension.
