### ISSUE TITLE
Extension does not work on Google websites on Opera

### ISSUE THREAD

**Issue by Nexer8** [luandersonn/Modern-scrollbar#12]
This extension has some issues with google pages when using Opera.
Example pages where the scrollbar does not change its appearance:
- https://www.google.com/finance/
- https://www.google.com/doodles
- https://www.google.com/search?client=opera&q=modern+scrollbar&sourceid=opera&ie=UTF-8&oe=UTF-8

**Comment by luandersonn** [comment]
Sorry, but the modern scrollbar only works in Chrome-based browsers

**Comment by Nexer8** [comment]
I don't really understand your answer since **Opera is a Chromium-based browser**. Please reopen this issue.

**Comment by luandersonn** [comment]
Can you shows a screenshot?

**Comment by luandersonn** [comment]
I don't know what is happening here, works fine on Chrome/Edge. Maybe an Opera bug?

**Comment by TheP2WKing** [comment]
You have to go to extension icon --> manage extension --> modern scrollbar --> set "allow access to search page results" to true

**Comment by lawki** [comment]
To add to what @TheP2WKing , one can directly go to this page opera://extensions and set "allow access to search page results" to fix the issue.

I think the issue is that Opera has a security feature where extensions can't see search results unless explicitly allowed by the user.

**Comment by luandersonn** [comment]
Thank you, @TheP2WKing and @lawki!
