### ISSUE TITLE
Text Offset in search bars when enabled

### ISSUE THREAD

**Issue by jenabaivab** [luandersonn/Modern-scrollbar#3]
Using the extension on edge from chrome store since the edge store version isn't updated to latest version.

**Without using extension-**

![image](https://user-images.githubusercontent.com/60446763/108628393-a8b4f700-7480-11eb-8ffa-04513305011b.png)

**Using extension-**
![image](https://user-images.githubusercontent.com/60446763/108628413-bff3e480-7480-11eb-8ee1-ebded741d2c0.png)

Can this be fixed?

**Comment by luandersonn** [comment]
Both are the same extension, the same version. **1.0.1.0**. Have you sure it is the Modern Scrollbar that is causing this?

**Edge version**
![image](https://user-images.githubusercontent.com/30560453/108630585-4938f600-7444-11eb-95b9-6dd17a1a0880.png)

**Chrome version**
![image](https://user-images.githubusercontent.com/30560453/108630766-3bd03b80-7445-11eb-974c-77a725a666e4.png)

**Default scrollbar, Modern Scrollbar disabled**
![image](https://user-images.githubusercontent.com/30560453/108630632-8d2bfb00-7444-11eb-84a1-12c4fd2d16d4.png)

**Comment by jenabaivab** [comment]
@luandersonn 100% because of the extension.
1 thing I forgot to mention, it may be caused by the new chromium build.
My primary browser is edge canary, which has chromium v90.
Facing issues in Edge canary, edge dev. 
Not reproducible in edge stable. I just checked it.

**Comment by luandersonn** [comment]
Oh, okay. They probably changed something on preview version (canary, dev). Maybe will be fixed on consumer version.

**Comment by jenabaivab** [comment]
Possible.
I use the dev build as my daily driver. If you have time, please try and see what's causing this problem. I understand you not prioritizing this, and it's totally fine if you don't. Just a small request that's all. No need to devote a lot of time, just a little is fine if you want.

Thank you for replying. Have a nice day. :)

**Comment by luandersonn** [comment]
Looks normal (Edge Canary). Can you confirm if the bug persists?
![image](https://user-images.githubusercontent.com/30560453/108786955-84761a80-7553-11eb-8b2c-2beeb3c85a2e.png)

**Comment by jenabaivab** [comment]
> Looks normal (Edge Canary). Can you confirm if the bug persists?

Yes, it still exists. It's everywhere, even in Github, see,

![image](https://user-images.githubusercontent.com/60446763/108787598-14d84d80-759c-11eb-919f-c3bdedc2410c.png)

**Comment by luandersonn** [comment]
This is confusing me 🤯

![image](https://user-images.githubusercontent.com/30560453/108787810-42e66f00-7555-11eb-82d8-b185ee576ff9.png)

What version is? Canary or Dev? Can you check if it's the lastest version?

**Comment by luandersonn** [comment]
My version: **90.0.806.0 canary (64 bits)**

**Comment by jenabaivab** [comment]
I don't believe it.

I just received the 90.0.806.0 update and the issue is fixed. Like about 10 mins back. It was present yesterday, today the update seems to rectify the problem. 
Good job Microsoft I guess...

**Comment by luandersonn** [comment]
Great news :)
