### ISSUE TITLE
[Request] Port to Mozilla Firefox

### ISSUE THREAD

**Issue by jenabaivab** [luandersonn/Modern-scrollbar#4]
Hello,

Is there any chance you would consider porting this extension to Firefox please ?
There is nothing this simple in the mozilla addon store.

**Comment by luandersonn** [comment]
Hello, @jenabaivab!

Unfortunately, Firefox's scrollbar is not fully customizable like Chromium's scrollbar. I tried to make a port last week. The only way to fully customize it is to use **Javascript**.  Using only CSS, I can change only the width (default and thin) and color:


### Default (Firefox already has buil-in dark scrollbar)
![02-26-21 - 23h-05m-22s](https://user-images.githubusercontent.com/30560453/109372214-2e70e200-7887-11eb-8f9b-4a6f4d874051.PNG)

### Modern
![02-26-21 - 23h-05m-29s](https://user-images.githubusercontent.com/30560453/109372234-46486600-7887-11eb-8426-784795b68d7b.PNG)

**Comment by jenabaivab** [comment]
There is another extension called Custom scrollbars, maybe that repo can serve as a guide.
Also, could you please share the code for the above modern scrollbar? Wish we could make them rounded around the edge as well.

**Comment by luandersonn** [comment]
@jenabaivab Add this on `css/scrollbar.css` file
```css
* {
    scrollbar-width: thin;
    scrollbar-color: rgba(127, 127, 127, 0.6) transparent;
}`

**Comment by jenabaivab** [comment]
@luandersonn I am actually using a material skin for firefox right now. You can find the chrome folder I have in my root profile directory uploaded here. What changes do I have to make in this please?


[chrome.zip](https://github.com/luandersonn/Modern-scrollbar/files/6056629/chrome.zip)

**Comment by luandersonn** [comment]
Sorry, I didn't understand

**Comment by jenabaivab** [comment]
Apologies, I have managed to get material scrollbar thanks to your code above. Thank you for that that. You can close this issue if you want.

**Comment by luandersonn** [comment]
Great news.
