### ISSUE TITLE
Dark mode and light mode manual select for user tq

### ISSUE THREAD

**Issue by zhenjie1999** [luandersonn/Modern-scrollbar#5]
Some website not sure is showing light mode of scroll bar but actually website is nearly dark mode.
Your can give user a website list each for light mode and dark mode setting

**Comment by zhenjie1999** [comment]
I forget which website, if future I have found it I will let you know.
Thank you for replying to me.

**Comment by arvinyorro** [comment]
I'm not getting a dark scrollbar on reddit

**Comment by zhenjie1999** [comment]
Thanks for the tip!
[image: image.png]

**Comment by luandersonn** [comment]
Because reddit doesn't set their site background to a dark color, keeping the default color (white). See how it would look if they did that:

![Reddit screenshot](https://user-images.githubusercontent.com/30560453/117549313-21533a80-b010-11eb-81d8-e39467ee20a2.png)

**Comment by luandersonn** [comment]
> Here is my view on reddit
> 
> ![image](https://user-images.githubusercontent.com/1425668/117559337-fb34a580-b0b6-11eb-8839-941238ac90bf.png)

Yes, they need to set the body background to black, but they didn't

**Comment by luandersonn** [comment]
Working on fix to reddit using js ;) (1.0.0.5)
![image](https://user-images.githubusercontent.com/30560453/132085128-9e7af410-d701-4f6e-a713-daf94e98cca9.png)
