### ISSUE TITLE
modern scoll bar doesn't work in pdf &new tab page

### ISSUE THREAD

**Issue by JolyonJostar** [luandersonn/Modern-scrollbar#8]
pdf:
![image](https://user-images.githubusercontent.com/61088063/125070945-38cfa200-e0eb-11eb-9b32-e69f2206c254.png)
new tab
![image](https://user-images.githubusercontent.com/61088063/125071074-66b4e680-e0eb-11eb-96dd-562bd02d71e4.png)

**Comment by luandersonn** [comment]
Unfortunately, there is no way to access the New Tab page (and others, PDF, Extensions...) :(

([source](https://codereview.chromium.org/2978953002/))

![js error](https://user-images.githubusercontent.com/30560453/125171099-bbf30580-e188-11eb-83f9-eac46c28dbef.png)
