### ISSUE TITLE
Update scrollbar UI to Windows 11/WinUI 2.6 style

### ISSUE THREAD

**Issue by muznyo** [luandersonn/Modern-scrollbar#9]
As you can see, Windows 11 uses new scrollbar across the system:
![image](https://user-images.githubusercontent.com/24987471/125169005-8b22c880-e1a8-11eb-9436-a4e5bd89917f.png)
![image](https://user-images.githubusercontent.com/24987471/125169014-94ac3080-e1a8-11eb-9cff-440212ca37a0.png)

Please consider updating scrollbar style to match the Windows 11 one

**Comment by luandersonn** [comment]
Waiting for Microsoft/Google approval
